# Generated by Django 5.0 on 2025-11-22 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillzone', '0004_message_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('barter', 'user')},
        ),
    ]
