# Generated by Django 5.0 on 2026-01-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillzone', '0005_alter_feedback_rating_alter_feedback_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='completed_by_from',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barter',
            name='completed_by_to',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='barter',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Admin Approved', 'Admin Approved'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
